[tool.poetry]
name = "ideal-pancake"
version = "0.1.0"
description = ""
authors = ["s0lvang <august.s.solvang@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8.5"
black = {version="*", allow-prereleases=true}
jupyter = "^1.0.0"
numpy = "^1.19.2"
pandas = "^1.1.2"
matplotlib = "^3.3.2"
pyEDFlib = "^0.1.18"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
